/**
 * @file objectiveTypes.js
 */

export const GET_OBJECTIVES_REQUEST = "GET_OBJECTIVES_REQUEST";
export const GET_OBJECTIVES_SUCCESS = "GET_OBJECTIVES_SUCCESS";
export const GET_OBJECTIVES_FAIL    = "GET_OBJECTIVES_FAIL";

export const CREATE_OBJECTIVE_REQUEST = "CREATE_OBJECTIVE_REQUEST";
export const CREATE_OBJECTIVE_SUCCESS = "CREATE_OBJECTIVE_SUCCESS";
export const CREATE_OBJECTIVE_FAIL    = "CREATE_OBJECTIVE_FAIL";

export const UPDATE_OBJECTIVE_REQUEST = "UPDATE_OBJECTIVE_REQUEST";
export const UPDATE_OBJECTIVE_SUCCESS = "UPDATE_OBJECTIVE_SUCCESS";
export const UPDATE_OBJECTIVE_FAIL    = "UPDATE_OBJECTIVE_FAIL";

export const DELETE_OBJECTIVE_REQUEST = "DELETE_OBJECTIVE_REQUEST";
export const DELETE_OBJECTIVE_SUCCESS = "DELETE_OBJECTIVE_SUCCESS";
export const DELETE_OBJECTIVE_FAIL    = "DELETE_OBJECTIVE_FAIL";

export const CLEAR_OBJECTIVE_ERROR = "CLEAR_OBJECTIVE_ERROR";
export const RESET_OBJECTIVE_STATE = "RESET_OBJECTIVE_STATE";