/**
 * @file profileTypes.js
 * @description Constantes des types d'actions Redux pour le profil.
 */

// GET
export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL    = "GET_PROFILE_FAIL";

// UPDATE
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL    = "UPDATE_PROFILE_FAIL";

// CREATE
export const CREATE_PROFILE_REQUEST = "CREATE_PROFILE_REQUEST";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_FAIL    = "CREATE_PROFILE_FAIL";

// DELETE
export const DELETE_PROFILE_REQUEST = "DELETE_PROFILE_REQUEST";
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";
export const DELETE_PROFILE_FAIL    = "DELETE_PROFILE_FAIL";

// UTILS
export const CLEAR_PROFILE_ERROR = "CLEAR_PROFILE_ERROR";
export const RESET_PROFILE_STATE = "RESET_PROFILE_STATE";