/**
 * @file transactionTypes.js
 */

// GET ALL
export const GET_TRANSACTIONS_REQUEST = "GET_TRANSACTIONS_REQUEST";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAIL    = "GET_TRANSACTIONS_FAIL";

// CREATE
export const CREATE_TRANSACTION_REQUEST = "CREATE_TRANSACTION_REQUEST";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_FAIL    = "CREATE_TRANSACTION_FAIL";

// UPDATE
export const UPDATE_TRANSACTION_REQUEST = "UPDATE_TRANSACTION_REQUEST";
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS";
export const UPDATE_TRANSACTION_FAIL    = "UPDATE_TRANSACTION_FAIL";

// DELETE ONE
export const DELETE_TRANSACTION_REQUEST = "DELETE_TRANSACTION_REQUEST";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_FAIL    = "DELETE_TRANSACTION_FAIL";

// DELETE MANY
export const DELETE_MANY_TRANSACTIONS_REQUEST = "DELETE_MANY_TRANSACTIONS_REQUEST";
export const DELETE_MANY_TRANSACTIONS_SUCCESS = "DELETE_MANY_TRANSACTIONS_SUCCESS";
export const DELETE_MANY_TRANSACTIONS_FAIL    = "DELETE_MANY_TRANSACTIONS_FAIL";

// UTILS
export const CLEAR_TRANSACTION_ERROR = "CLEAR_TRANSACTION_ERROR";
export const RESET_TRANSACTION_STATE = "RESET_TRANSACTION_STATE";